### PR TITLE
Change translation of "name" to name in EN locale

### PR DESCRIPTION
**Pull request by LaurensN**
Build also fails locally for me on master branch, can you confirm this?

### CODE REVIEW

**Comment by damoiser** [comment]
Hi @LaurensN  sorry for my late feedback, please refresh this PR with the latest master, pipeline errors has been fixed. Will then merge it

**Comment by damoiser** [comment]
Hi @LaurensN  sorry for my late feedback, please refresh this PR with the latest master, pipeline errors has been fixed. Will then merge it

**Comment by LaurensN** [comment]
Hi @damoiser, done.

**Comment by damoiser** [comment]
Thanks a lot @LaurensN for your contribution, your fixes have been published in the v1.0.10 version of the gem

**Pull request merged**
