### PR TITLE
Remove rake requirement from gemspec

### PR DESCRIPTION
**Pull request by RandieM**
As discussed in issue #12.

### CODE REVIEW

**Comment by damoiser** [comment]
can you please @RandieM merge the current master to your PR again? Switch to CircleCI is now done, so that I can see that with your changes all tests will still work properly, thanks!

**Comment by RandieM** [comment]
Done!

**Comment by damoiser** [comment]
thx, hope will work when merged because the CI was disabled for forked branches, from the next one should be triggered correctly

**Comment by damoiser** [comment]
changes are now present in the published v1.0.4 of the gem
* https://rubygems.org/gems/qr-bills/versions/1.0.4

**Pull request merged**
